#!/bin/bash

# 1. Telegram Local API Server start karein background mein
echo "Starting Telegram API Server..."
/usr/local/bin/telegram-bot-api --local \
    --api-id=20984573 \
    --api-hash=9f694b45564ad23675aa3a01ffa9b7ca \
    --http-port=8081 \
    --http-ip-address=127.0.0.1 \
    --dir=/app &

# API server ko puri tarah start hone ke liye 3 seconds wait karein
echo "Waiting for API server to start..."
sleep 3

# 2. Python Bot start karein
echo "Starting Secure Drive Bot..."
python3 main.py
